country_codes = {
    'USA/Canada': '1',
    'Russia': '7',
    'Egypt': '20',
    'South Africa': '27',
    'Greece': '30',
    'Netherlands': '31',
    'Belgium': '32',
    'France': '33',
    'Spain': '34',
    'Italy': '39',
    'Switzerland': '41',
    'United Kingdom': '44',
    'Sweden': '46',
    'Norway': '47',
    'Poland': '48',
    'Germany': '49',
    'Brazil': '55',
    'Malaysia': '60',
    'Australia': '61',
    'Indonesia': '62',
    'Philippines': '63',
    'Singapore': '65',
    'Thailand': '66',
    'Japan': '81',
    'South Korea': '82',
    'China': '86',
    'Turkey': '90',
    'India': '91',
    'Pakistan': '92',
    'Afghanistan': '93',
    'Sri Lanka': '94',
    'Iran': '98',
    'Morocco': '212',
    'Algeria': '213',
    'Tunisia': '216',
    'Libya': '218',
    'Nigeria': '234',
    'Kenya': '254',
    'Tanzania': '255',
    'Uganda': '256',
    'Zambia': '260',
    'Zimbabwe': '263',
    'Portugal': '351',
    'Iraq': '964',
    'Kuwait': '965',
    'Saudi Arabia': '966',
    'Oman': '968',
    'United Arab Emirates': '971',
    'Israel': '972',
    'Qatar': '974'
}